project:
  type: website
  # output-dir: docs # Pasta para o GitHub Pages

website:
  title: "ΛΣ" # Título principal do site
  page-navigation: true
  description: "Portfólio de projetos de Alexssandro Oliveira e Leticia Haifa"
  
  # 1. Barra de Navegação (Navbar)
  navbar:
    search: true
    collapse: false
    left:
      - text: "<i class='bi bi-house'></i> Início"
        href: index.qmd
      - text: "<i class='bi bi-file-earmark-person'></i> Sobre Nós"
        href: about.qmd
      # Menu de Projetos (já com o link do MLD)
      - text: "<i class='bi bi-journal-code'></i> Projetos"
        menu:
          - href: projeto-mld.qmd
            text: "Projeto 1: Modelos Lineares Dinâmicos"
          - href: projeto-adl.qmd
            text: "Projeto 2: Analise de dados longitudinais"

            
  # 2. Rodapé (Footer) - O local correto para os nomes
  page-footer:
    left: 
      - text: "<b>Colaboradores: </b>" # Uso de <b> garante o negrito
      - text: " Alexssandro da S. Oliveira<sup>1</sup>"
      - text: "Jakelinne Amazonas Gadelha<sup>2</sup>"
      - text: "Letícia Haifa do N. Mattos<sup>3</sup>"

    center: 
      - text: "E pelas primeiras vezes, o que passou, passou... comece de novo."
        href: mailto:alexssandrosg@gmail.com # (Email opcional)

# 3. Formato de Saída (HTML)
format: 
  html: 
    theme: flatly # IMPORTANTE: Remove o tema padrão para usar 100% o nosso CSS
    css: styles.css
    
    # Importa as fontes profissionais do Google e o CSS extra
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Fira+Code&display=swap" rel="stylesheet">
          
          <!-- Estilo CSS para detalhes/sumário -->
          <style>
          details > summary {
            color: #132a13;
            font-weight: bold;
            cursor: pointer;
          }
          </style>
    
    # Configurações de Layout
    fontsize: 0.9em
    margin-left: 0em
    margin-right: 0em
    margin-bottom: 0em
    margin-top: -1em
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Mostrar/Ocultar Código R"

# 4. Configuração do R
execute:
  freeze: auto    # "Congela" resultados
  message: false  # Ocultar mensagens 
  warning: false  # Ocultar warnings 

